version: '3.8'
services:
    poe-news:
      image: poe-news-discord-bot:${TAG}
      volumes:
          - poe-news-data:/poe-news/data
          - poe-news-config:/poe-news/config
      restart: always
volumes:
    poe-news-data:
    poe-news-config: